
'use server';

/**
 * @fileOverview AI tool to generate notes based on course, year, subject, and topic inputs.
 *
 * - generateNotes - A function that handles the note generation process.
 * - GenerateNotesInput - The input type for the generateNotes function.
 * - GenerateNotesOutput - The return type for the generateNotes function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateNotesInputSchema = z.object({
  course: z.string().describe('The course for which notes are being generated (e.g., B.Pharm, D.Pharm).'),
  year: z.string().describe('The academic year of the course.'),
  subject: z.string().describe('The subject of the notes.'),
  topic: z.string().describe('The specific topic for the notes.'),
  universitySyllabus: z.string().optional().describe('The specific university, syllabus, or competitive exam the notes should be tailored for (e.g., "Gujarat Technological University", "GPAT Exam").'),
});
export type GenerateNotesInput = z.infer<typeof GenerateNotesInputSchema>;

const GenerateNotesOutputSchema = z.object({
  notes: z.string().describe('The generated notes in Markdown format.'),
});
export type GenerateNotesOutput = z.infer<typeof GenerateNotesOutputSchema>;

export async function generateNotes(input: GenerateNotesInput): Promise<GenerateNotesOutput> {
  return generateNotesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateNotesPrompt',
  input: {schema: GenerateNotesInputSchema},
  output: {schema: GenerateNotesOutputSchema},
  prompt: `You are an expert Pharmacy Faculty member from a top-tier institution, tasked with creating high-quality study material for the phamA2G platform. Your work must be impeccable, accurate, and tailored for competitive examinations.

**Core Directive:** Generate comprehensive, well-structured study notes based on the user's request. The content must be synthesized **strictly** from information found in standard, authoritative pharmacy textbooks (e.g., Rang & Dale's Pharmacology, Goodman & Gilman, Lachman's Industrial Pharmacy, Kokate's Pharmacognosy, Trease and Evans).

**Syllabus/Exam Prioritization (Crucial):**
- If the user provides a **University, Syllabus, or Exam name** (e.g., "GPAT", "NIPER", "PCI Syllabus"), this is your **PRIMARY directive**.
- You MUST act as an examiner for that specific context.
- The notes' scope, depth, and emphasis on topics MUST be 100% aligned with that curriculum or exam pattern. High-yield topics for that specific exam should be given prominence.

**Output Formatting Rules (Strictly Enforced):**
1.  **Markdown:** Use Markdown for all formatting.
2.  **Structure:**
    - Start with a clear **Title** (H1).
    - Follow with a brief **Introduction**.
    - Use **Headings and Subheadings** (H2, H3, H4) to organize content logically.
    - **Bold** all important keywords, drug names, and key terms.
    - Use bullet points, numbered lists, or tables for clarity.
    - End with a **Conclusion**.
    - After the conclusion, add a **"Quick Recap"** section inside a blockquote, summarizing 4-5 essential takeaways.
3.  **Language & Tone:**
    - **D.Pharm:** Use simpler, direct language.
    - **B.Pharm/Competitive Exam:** Use a precise, academic tone.
4.  **Footer:** The absolute last line of your output MUST be:
    *Generated by phamA2G AI Notes Generator*

**User's Request:**
- **Course**: {{ course }}
- **Year**: {{ year }}
- **Subject**: {{ subject }}
- **Topic**: {{ topic }}
{{#if universitySyllabus}}- **Syllabus/Exam Focus**: {{ universitySyllabus }}{{/if}}

Proceed to generate the notes now, adhering to all directives.
`,
});

const generateNotesFlow = ai.defineFlow(
  {
    name: 'generateNotesFlow',
    inputSchema: GenerateNotesInputSchema,
    outputSchema: GenerateNotesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
