
'use server';

/**
 * @fileOverview AI tool to generate notes based on course, year, subject, and topic inputs.
 *
 * - generateNotes - A function that handles the note generation process.
 * - GenerateNotesInput - The input type for the generateNotes function.
 * - GenerateNotesOutput - The return type for the generateNotes function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateNotesInputSchema = z.object({
  course: z.string().describe('The course for which notes are being generated (e.g., B.Pharm, D.Pharm).'),
  year: z.string().describe('The academic year of the course.'),
  subject: z.string().describe('The subject of the notes.'),
  topic: z.string().describe('The specific topic for the notes.'),
  universitySyllabus: z.string().optional().describe('The specific university, syllabus, or competitive exam the notes should be tailored for (e.g., "Gujarat Technological University", "GPAT Exam").'),
});
export type GenerateNotesInput = z.infer<typeof GenerateNotesInputSchema>;

const GenerateNotesOutputSchema = z.object({
  notes: z.string().describe('The generated notes in Markdown format.'),
});
export type GenerateNotesOutput = z.infer<typeof GenerateNotesOutputSchema>;

export async function generateNotes(input: GenerateNotesInput): Promise<GenerateNotesOutput> {
  return generateNotesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateNotesPrompt',
  input: {schema: GenerateNotesInputSchema},
  output: {schema: GenerateNotesOutputSchema},
  prompt: `You are a highly experienced academic assistant and expert tutor specializing in Pharmacy.

Your job is to generate top-quality, well-organized, and deeply informative study notes based on the user's topic. These notes will be shown on the “phamA2G” platform and should resemble a mini textbook chapter for pharmacy students.

✦ Your Output MUST follow this structure:
- Use **Markdown formatting**
- Begin with a clear **title**
- Use **H2 and H3** for headings/subheadings
- **Bold** keywords and terms
- Use bullet points or tables where helpful
- Add a **"Quick Recap"** at the end (a short box with 4–5 key summary points)

✦ Quality Guidelines:
- Stick closely to **standard pharmacy textbooks** like Kokate, Trease & Evans, Rang & Dale, etc.
- The language should be tailored to the course/year:
  - D.Pharm → simpler, student-friendly
  - B.Pharm → deeper, academic tone with references if needed
- Avoid copy-paste tone, instead synthesize content
- **Crucially, if the user provides a University/Syllabus/Exam, you MUST tailor the content to that specific context. Prioritize the topics and depth relevant to that curriculum or exam pattern.**

User Input:
- **Course**: {{ course }}
- **Year**: {{ year }}
- **Subject**: {{ subject }}
- **Topic**: {{ topic }}
{{#if universitySyllabus}}- **Syllabus/Exam Focus**: {{ universitySyllabus }}{{/if}}

Output only the Markdown notes with title, headings, and content – styled like a professional textbook chapter.

Add a footer note or watermark:
*Generated by phamA2G AI Notes Generator*
`,
});

const generateNotesFlow = ai.defineFlow(
  {
    name: 'generateNotesFlow',
    inputSchema: GenerateNotesInputSchema,
    outputSchema: GenerateNotesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
